# OrangeFox Recovery build settings for Poco C40 (frost)
export FOX_AB_DEVICE=1
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export OF_NO_MIUI_PATCH_WARNING=1
export OF_SCREEN_H=1650
export OF_STATUS_H=80
export OF_STATUS_INDENT_LEFT=40
export OF_STATUS_INDENT_RIGHT=40
export OF_CLOCK_POS=1
export OF_USE_GREEN_LED=0
export OF_FLASHLIGHT_ENABLE=0
export FOX_MAINTAINER_PATCH_VERSION=1
export OF_MAINTAINER="Fakezay"
